### ISSUE TITLE
I failed to compile using webpack

### ISSUE THREAD

**Issue by yyhappynice** [piotrwitek/preact-redux-typescript-rollup-starter#1]
This example is very nice. but my project compiles using webpack.  
my webpack config :
```
alias: {
  'react': 'preact-compat',
  'react-dom': 'preact-compat'
}
```
but my app.tsx `import React from 'react'` is failed. command return` Cannot find module 'react'.`
Is my configuration a problem?   feel `preact-compat` is not work    [my project](https://github.com/yi-cli/preact) 
Hope to give an example of webpack compilation.  Be deeply grateful !

**Comment by piotrwitek** [comment]
hello, sorry but I cannot help you, this is rollup specific project setup and I didn't tested it with webpack workflow so my experience is limited.
